name: 'Robert Deusser'
description: 'Truncates a file'
author: 'Robert Deusser'
inputs:
  file:
    required: true
    description: 'Path to file to truncate'
  characterlimit:
    required: true
    description: 'Action will truncate the number of characters in a file to this number'
  removeLastLine:
    required: false
    description: 'Sometimes truncating can cutoff the information in the last line so if true, this removes it'
runs:
  using: 'node16'
  main: 'dist/index.js'
